/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.test.meetingroom.api;

import com.test.meetingroom.model.BookingDto;
import com.test.meetingroom.model.BookingRequest;
import com.test.meetingroom.model.CreateBooking400Response;
import com.test.meetingroom.model.ErrorResponse;
import com.test.meetingroom.model.ValidationError;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "Booking", description = "Booking operations")
public interface BookingApi {

    default BookingApiDelegate getDelegate() {
        return new BookingApiDelegate() {};
    }

    /**
     * POST /api/bookings/add : Create a new booking
     *
     * @param bookingRequest  (required)
     * @return The created booking (status code 201)
     *         or Invalid input or validation error (status code 400)
     *         or Booking conflict (status code 409)
     */
    @Operation(
        operationId = "createBooking",
        summary = "Create a new booking",
        tags = { "Booking" },
        responses = {
            @ApiResponse(responseCode = "201", description = "The created booking", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BookingDto.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid input or validation error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateBooking400Response.class))
            }),
            @ApiResponse(responseCode = "409", description = "Booking conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/bookings/add",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BookingDto> createBooking(
        @Parameter(name = "BookingRequest", description = "", required = true) @Valid @RequestBody BookingRequest bookingRequest
    ) {
        return getDelegate().createBooking(bookingRequest);
    }


    /**
     * DELETE /api/bookings/{id} : Delete a booking
     *
     * @param id  (required)
     * @return Successfully deleted (status code 200)
     *         or Booking not found (status code 404)
     */
    @Operation(
        operationId = "deleteBooking",
        summary = "Delete a booking",
        tags = { "Booking" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successfully deleted"),
            @ApiResponse(responseCode = "404", description = "Booking not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/bookings/{id}",
        produces = { "application/json" }
    )
    default ResponseEntity<Void> deleteBooking(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        return getDelegate().deleteBooking(id);
    }


    /**
     * GET /api/admin/allBooking : List bookings
     *
     * @return List of all bookings (status code 200)
     */
    @Operation(
        operationId = "getBookings",
        summary = "List bookings",
        tags = { "Booking" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of all bookings", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = BookingDto.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/admin/allBooking",
        produces = { "application/json" }
    )
    default ResponseEntity<List<BookingDto>> getBookings(
        
    ) {
        return getDelegate().getBookings();
    }


    /**
     * GET /api/bookings : List bookings by meeting room
     *
     * @param roomId Filter by meeting room (required)
     * @return List of bookings (status code 200)
     *         or Validation error (status code 400)
     */
    @Operation(
        operationId = "getBookingsByMeetingRoom",
        summary = "List bookings by meeting room",
        tags = { "Booking" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of bookings", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = BookingDto.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Validation error", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ValidationError.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/bookings",
        produces = { "application/json" }
    )
    default ResponseEntity<List<BookingDto>> getBookingsByMeetingRoom(
        @NotNull @Parameter(name = "roomId", description = "Filter by meeting room", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "roomId", required = true) Integer roomId
    ) {
        return getDelegate().getBookingsByMeetingRoom(roomId);
    }

}
