/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.test.meetingroom.api;

import com.test.meetingroom.model.BookingDto;
import com.test.meetingroom.model.BookingRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "Booking", description = "Booking stuff")
public interface BookingApi {

    default BookingApiDelegate getDelegate() {
        return new BookingApiDelegate() {};
    }

    /**
     * GET /api/admin/bookings : Listázza a foglalásokat
     *
     * @param roomId Szűrés tárgyaló szerint (required)
     * @return Foglalások listája (status code 200)
     */
    @Operation(
        operationId = "bookings",
        summary = "Listázza a foglalásokat",
        tags = { "Booking" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Foglalások listája", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = BookingDto.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/admin/bookings",
        produces = { "application/json" }
    )
    default ResponseEntity<List<BookingDto>> bookings(
        @NotNull @Parameter(name = "roomId", description = "Szűrés tárgyaló szerint", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "roomId", required = true) Integer roomId
    ) {
        return getDelegate().bookings(roomId);
    }


    /**
     * POST /api/bookings/add : Új foglalás létrehozása
     *
     * @param bookingRequest  (required)
     * @return A létrehozott foglalás (status code 200)
     */
    @Operation(
        operationId = "createBooking",
        summary = "Új foglalás létrehozása",
        tags = { "Booking" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A létrehozott foglalás", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BookingDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/bookings/add",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BookingDto> createBooking(
        @Parameter(name = "BookingRequest", description = "", required = true) @Valid @RequestBody BookingRequest bookingRequest
    ) {
        return getDelegate().createBooking(bookingRequest);
    }


    /**
     * DELETE /api/bookings/{id} : Foglalás törlése
     *
     * @param id  (required)
     * @return Sikeres törlés (status code 204)
     */
    @Operation(
        operationId = "deleteBooking",
        summary = "Foglalás törlése",
        tags = { "Booking" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Sikeres törlés")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/bookings/{id}"
    )
    default ResponseEntity<Void> deleteBooking(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        return getDelegate().deleteBooking(id);
    }

}
