/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.test.meetingroom.api;

import com.test.meetingroom.model.MeetingRoom;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "Room", description = "Room stuff")
public interface RoomApi {

    default RoomApiDelegate getDelegate() {
        return new RoomApiDelegate() {};
    }

    /**
     * GET /api/rooms : Listázza a tárgyalókat
     *
     * @return Tárgyalók listája (status code 200)
     */
    @Operation(
        operationId = "getRooms",
        summary = "Listázza a tárgyalókat",
        tags = { "Room" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Tárgyalók listája", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = MeetingRoom.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/rooms",
        produces = { "application/json" }
    )
    default ResponseEntity<List<MeetingRoom>> getRooms(
        
    ) {
        return getDelegate().getRooms();
    }

}
